#Basic Settings #
##################

# Image resolution Set to empty object (`{ }`) to use default resolution.
#resolution: { }
width: 1920
height: 1088

# Twitter application authentication
app_key: 'YOUR TWITTER APP KEY'
app_secret: 'YOUR TWITTER APP SECRET'
oauth_token: 'YOUR TWITTER OAUTH TOKEN'
oauth_token_secret: 'YOUR TWITTER OAUTH SECRET'

# how many images to take before declaring a new "most people" winner
how_many_to_check: 30
visualize_obj_detection: False
testing_locally: False
min_confidence: 0.25

# The number of images to capture.
#total_images: 20

# The interval between captures (in seconds).
interval: 2

# Whether to create an animated gif after capturing the time-lapse images.
create_gif: True

# Whether to create an video after capturing the time-lapse images.
create_video: True

#####################
# Advanced settings #
#####################

# ISO value. 0 = auto, 60-800 for manual ISO.
iso: 0

# Shutter speed. 0 = auto, else value in microseconds (seconds * 1000000).
shutter_speed: 0

# White balance. Set to empty object (`{ }`) to use auto white balance.
white_balance: { }
  # red_gain: 1.3
  # blue_gain: 1.75

# Rotate the images taken by the camera. Possible value are 0, 90, 180 or 270
rotation: 0

